framework:
    messenger:
        transports:
            # Uncomment the following line to enable a transport named "amqp"
            # amqp: '%env(MESSENGER_TRANSPORT_DSN)%'
            #amqp: '%env(MESSENGER_TRANSPORT_DSN)%'
            amqp: enqueue://default

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': amqp
            'Identity\Domain\Model\User\Command\NotifyConfirmMessageForNewUserRegistration': amqp

            'Identity\Domain\Model\User\Command\SmsNotificationCommand': amqp
