prooph_event_store:
    stores:
        default:
            event_store: 'app.event_store.default'
        #identity:
            #event_store: 'app.event_store.identity'

services:
    _defaults:
        public: false

    Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator: ~
