version: '3'

services:
  app:
    image: webdevops/php-nginx-dev:7.4
    user: application
    working_dir: /app
    environment:
      WEB_DOCUMENT_ROOT: /app
      WEB_DOCUMENT_INDEX: public/index.php
    ports:
      - 80:80
    volumes:
      - .:/app
    depends_on:
      - mysql
      - rmq

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_DATABASE=s4-gothinkster

  rmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"