<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Identity\Domain\Model\Identity;

final class HashPassword
{
    private $hashPassword;

    public function __construct(string $hashPassword)
    {
        $this->hashPassword = $hashPassword;
    }

    public function hashPassword(): string
    {
        return $this->hashPassword;
    }

    public function withHashPassword(string $hashPassword): HashPassword
    {
        return new self($hashPassword);
    }

    public static function fromString(string $hashPassword): HashPassword
    {
        return new self($hashPassword);
    }

    public function toString(): string
    {
        return $this->hashPassword;
    }

    public function __toString(): string
    {
        return $this->hashPassword;
    }

    public function equals(HashPassword $hashPassword): bool
    {
        return $this->hashPassword === $hashPassword->hashPassword;
    }
}
