<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Identity\Domain\Model\User;

final class User
{
    private $userId;
    private $email;

    public function __construct(UserId $userId, Email $email)
    {
        $this->userId = $userId;
        $this->email = $email;
    }

    public function userId(): UserId
    {
        return $this->userId;
    }

    public function email(): Email
    {
        return $this->email;
    }

    public function withUserId(UserId $userId): User
    {
        return new self($userId, $this->email);
    }

    public function withEmail(Email $email): User
    {
        return new self($this->userId, $email);
    }
}
