<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Identity\Domain\Model\User\Command;

final class RegisterPippo extends \Prooph\Common\Messaging\Command
{
    use \Prooph\Common\Messaging\PayloadTrait;

    public const MESSAGE_NAME = 'Identity\Domain\Model\User\Command\RegisterPippo';

    protected $messageName = self::MESSAGE_NAME;

    public function firstName(): string
    {
        return $this->payload['firstName'];
    }

    public static function with(string $firstName): RegisterPippo
    {
        return new self([
            'firstName' => $firstName,
        ]);
    }

    protected function setPayload(array $payload): void
    {
        if (!isset($payload['firstName']) || !\is_string($payload['firstName'])) {
            throw new \InvalidArgumentException("Key 'firstName' is missing in payload or is not a string");
        }

        $this->payload = $payload;
    }
}
