<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Member\Domain\Model\User\Event;

final class UserWasMarkedAsUnfollowed extends \Prooph\Common\Messaging\DomainEvent
{
    use \Prooph\Common\Messaging\PayloadTrait;

    public const MESSAGE_NAME = 'Member\Domain\Model\User\Event\UserWasMarkedAsUnfollowed';

    protected $messageName = self::MESSAGE_NAME;

    private $userId;
    private $unfollowedUser;

    public function userId(): string
    {
        if (null === $this->userId) {
            $this->userId = $this->payload['userId'];
        }

        return $this->userId;
    }

    public function unfollowedUser(): string
    {
        if (null === $this->unfollowedUser) {
            $this->unfollowedUser = $this->payload['unfollowedUser'];
        }

        return $this->unfollowedUser;
    }

    public static function with(string $userId, string $unfollowedUser): userWasMarkedAsUnfollowed
    {
        return new self([
            'userId' => $userId,
            'unfollowedUser' => $unfollowedUser,
        ]);
    }

    protected function setPayload(array $payload): void
    {
        if (!isset($payload['userId']) || !\is_string($payload['userId'])) {
            throw new \InvalidArgumentException("Key 'userId' is missing in payload or is not a string");
        }

        if (!isset($payload['unfollowedUser']) || !\is_string($payload['unfollowedUser'])) {
            throw new \InvalidArgumentException("Key 'unfollowedUser' is missing in payload or is not a string");
        }

        $this->payload = $payload;
    }
}
